-- Generated by scripts/update-catalog.sh from
-- https://addons.peavers.io/data/updater-catalog.json
-- Do not edit by hand; the release workflow refreshes this file.
local _, PC = ...

PC.AddonCatalog = {
    generatedAt = "2026-07-19T13:47:32Z",
    addons = {
        {
            folder = "BetterTogether",
            name = "Better Together",
            description = "Partner readiness dashboard for duo play.",
            tags = { "social", "utility" },
        },
        {
            folder = "PeaversAlwaysSquare",
            name = "Peavers Always Square",
            description = "Automatically sets the tank's raid icon as a square when in a party",
            tags = { "combat", "party", "mythic+" },
        },
        {
            folder = "PeaversBestInSlot",
            name = "Peavers Best In Slot",
            description = "Shows Best in Slot gear information in item tooltips",
            tags = { "gear", "best-in-slot" },
        },
        {
            folder = "PeaversBestInSlotData",
            name = "Peavers Best In Slot Data",
            description = "Best in Slot gear data for PeaversBestInSlot and others",
            tags = { "gear", "best-in-slot", "data", "library" },
        },
        {
            folder = "PeaversCVars",
            name = "Peavers CVars",
            description = "Manage and apply console variables with login persistence.",
            tags = { "utility", "settings", "configuration" },
        },
        {
            folder = "PeaversCommons",
            name = "Peavers Commons",
            description = "Common functionality for Peavers addons",
            tags = { "library", "utility", "framework" },
        },
        {
            folder = "PeaversConfig",
            name = "Peavers Config",
            description = "Centralized configuration for all Peavers addons",
            tags = { "utility", "configuration" },
        },
        {
            folder = "PeaversConsumables",
            name = "Peavers Consumables",
            description = "Shows the best consumables, enchants and gems for your spec and searches them on the Auction House",
            tags = { "consumables", "enchants", "auction-house" },
        },
        {
            folder = "PeaversConsumablesData",
            name = "Peavers Consumables Data",
            description = "Best consumable, enchant and gem data for PeaversConsumables and others",
            tags = { "consumables", "enchants", "data", "library" },
        },
        {
            folder = "PeaversCurrencyData",
            name = "Peavers Currency Data",
            description = "Real-time currency exchange rates and WoW token prices",
            tags = { "currency", "library", "data" },
        },
        {
            folder = "PeaversDynamicStats",
            name = "Peavers Dynamic Stats",
            description = "Displays secondary stats (haste, crit, mastery, versatility) in a movable frame",
            tags = { "combat", "bars" },
        },
        {
            folder = "PeaversGetThere",
            name = "Peavers Get There",
            description = "Search any location and get guided there",
            tags = { "travel", "map", "utility" },
        },
        {
            folder = "PeaversGetThereData",
            name = "Peavers Get There Data",
            description = "Travel graph, teleport and location data for PeaversGetThere and others",
            tags = { "travel", "navigation", "data", "library" },
        },
        {
            folder = "PeaversIconSearch",
            name = "Peavers Icon Search",
            description = "Adds an item search box to the transmog outfit icon picker",
            tags = { "transmog", "ui", "utility" },
        },
        {
            folder = "PeaversIconSearchData",
            name = "Peavers Icon Search Data",
            description = "Item name to icon data for PeaversIconSearch and others",
            tags = { "icons", "transmog", "data", "library" },
        },
        {
            folder = "PeaversItemLevel",
            name = "Peavers Item Level",
            description = "Displays player item levels in a movable frame",
            tags = { "group", "bars" },
        },
        {
            folder = "PeaversNeedThat",
            name = "Peavers Need That",
            description = "Monitors loot drops in M+ dungeons and provides quick whisper dialogs to ask for items",
            tags = { "mythic-plus", "loot", "utility" },
        },
        {
            folder = "PeaversPerformance",
            name = "Peavers Performance",
            description = "One-click graphics presets for more FPS - transparently",
            tags = { "performance", "graphics", "fps" },
        },
        {
            folder = "PeaversRealValue",
            name = "Peavers Real Value",
            description = "Shows the real-world dollar value of items based on their auction house price",
            tags = { "currency", "tooltip" },
        },
        {
            folder = "PeaversRemembersYou",
            name = "Peavers Remembers You",
            description = "Records players you group with and notifies you when you meet them again",
            tags = { "raid", "party", "group" },
        },
        {
            folder = "PeaversSystemBars",
            name = "Peavers System Bars",
            description = "Displays FPS and latency as visual status bars",
            tags = { "utility", "bars", "performance" },
        },
        {
            folder = "PeaversTalents",
            name = "Peavers Talents",
            description = "Pick the latest talent builds from wowcompare.io.",
            tags = { "talents" },
        },
        {
            folder = "PeaversTalentsData",
            name = "Peavers Talents Data",
            description = "Datasource for PeaversTalents and others",
            tags = { "talents", "data", "library" },
        },
    },
}
