# Regenerates src/Core/AddonCatalog.lua from the addons.peavers.io updater
# catalog. WoW addons cannot fetch at runtime, so the catalog is bundled and
# refreshed here (locally, or by the update-catalog job before each release).
$ErrorActionPreference = 'Stop'

$url = 'https://addons.peavers.io/data/updater-catalog.json'
$out = Join-Path $PSScriptRoot '..\src\Core\AddonCatalog.lua'

$catalog = Invoke-RestMethod -Uri $url

function ConvertTo-LuaString([string]$s) {
    if ($null -eq $s) { return '' }
    $s.Replace('\', '\\').Replace('"', '\"') -replace "`r|`n", ' '
}

function ConvertTo-DisplayName([string]$folder) {
    $folder -creplace '([a-z0-9])([A-Z])', '$1 $2'
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('-- Generated by scripts/update-catalog.ps1 from')
$lines.Add("-- $url")
$lines.Add('-- Do not edit by hand; the release workflow refreshes this file.')
$lines.Add('local _, PC = ...')
$lines.Add('')
$lines.Add('PC.AddonCatalog = {')
$lines.Add("    generatedAt = `"$($catalog.generated_at)`",")
$lines.Add('    addons = {')

foreach ($addon in ($catalog.addons | Sort-Object id)) {
    $tags = ($addon.tags | ForEach-Object { '"' + (ConvertTo-LuaString $_) + '"' }) -join ', '
    $lines.Add('        {')
    $lines.Add("            folder = `"$(ConvertTo-LuaString $addon.folder)`",")
    $lines.Add("            name = `"$(ConvertTo-LuaString (ConvertTo-DisplayName $addon.folder))`",")
    $lines.Add("            description = `"$(ConvertTo-LuaString $addon.description)`",")
    $lines.Add("            tags = { $tags },")
    $lines.Add('        },')
}

$lines.Add('    },')
$lines.Add('}')

Set-Content -Path $out -Value ($lines -join "`n") -Encoding UTF8 -NoNewline
Add-Content -Path $out -Value "`n" -NoNewline

Write-Host "Wrote $out ($($catalog.addons.Count) addons)"
