#!/usr/bin/env bash
# Regenerates src/Core/AddonCatalog.lua from the addons.peavers.io updater
# catalog. WoW addons cannot fetch at runtime, so the catalog is bundled and
# refreshed here (locally, or by the update-catalog job before each release).
set -euo pipefail
cd "$(dirname "$0")/.."

URL="https://addons.peavers.io/data/updater-catalog.json"
OUT="src/Core/AddonCatalog.lua"

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
curl -fsSL "$URL" -o "$tmp"

{
    echo "-- Generated by scripts/update-catalog.sh from"
    echo "-- $URL"
    echo "-- Do not edit by hand; the release workflow refreshes this file."
    echo "local _, PC = ..."
    echo ""
    echo "PC.AddonCatalog = {"
    jq -r '"    generatedAt = \"\(.generated_at)\","' "$tmp"
    echo "    addons = {"
    jq -r '
        def lua: gsub("\\\\"; "\\\\") | gsub("\""; "\\\"") | gsub("\r|\n"; " ");
        def display: gsub("(?<a>[a-z0-9])(?<b>[A-Z])"; "\(.a) \(.b)");
        .addons | sort_by(.id) | .[] |
        "        {\n" +
        "            folder = \"\(.folder | lua)\",\n" +
        "            name = \"\(.folder | display | lua)\",\n" +
        "            description = \"\(.description // "" | lua)\",\n" +
        "            tags = { \([.tags // [] | .[] | "\"\(lua)\""] | join(", ")) },\n" +
        "        },"
    ' "$tmp"
    echo "    },"
    echo "}"
} > "$OUT"

echo "Wrote $OUT ($(jq '.addons | length' "$tmp") addons)"
